export interface Customer {
    id: string;        // Unique customer ID
    firstName: string;
    lastName: string;
    phone: string;
    address: string;
  }

  export interface Employee {
    id: string; // Auto-generated by backend
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    position: string;
    salary: number;
  }

  export interface Supplier {
    id: string; // Auto-generated by backend
    name: string;
    email: string;
    phone: string;
    address: string;
  }

  export interface FlowerBoquet {
    id: string; // Backend-generated ID
    name: string;
    description: string;
    price: number;
    stock: number;
    supplierId: string;
  }

  export interface OrderDetail {
    id: string;  // Auto-generated by backend
    orderId: string;
    flowerBouquetId: string;
    quantity: number;
    price: number;
  }

  export interface Order {
    id: string;  // Auto-generated by backend
    totalAmount: number;
    date: string;
    customerId: string;  // Ensure this remains a string (matches backend)
}